version: 2

builds:
  - id: sql-query
    main: .
    binary: sql-query
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X sql-query/cmd.version={{.Version}}
      - -X sql-query/cmd.commit={{.Commit}}
      - -X sql-query/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc

release:
  github:
    owner: user-zouyu
    name: sql-query
  name_template: "{{.Tag}}"
